# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            HMT documentation
tagline:          'Technical documentation for editors and contributors'
description:      ''
baseurl: '/hmt-docs/'
 

links:
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: Prerequisite technologies
    url: /tech
  - title: The HMT VM
    url: /vm
  - title: Foundational work
    url: /dse
  - title: '"Total editing"'
    url: /totaled
  - title: Tips
    url: /tips
